### ISSUE TITLE
Super user - Create movies

### ISSUE THREAD

**Issue by jagestedt** [chas-academy/u05-imdb-clon-u05-team-9-angels#76]
Under dashboard

**Comment by LinusUnghammar** [comment]
I created a branch "create-movie", 
in the dashboard folder there is a blade called create movie
we will just have to add a form, i think maybe we can use the store method in moviecontroller to create new movies

**Comment by jagestedt** [comment]
have you pushed it? or is it on main?

**Comment by LinusUnghammar** [comment]
no this is on branch "create-movie" , i was thinking that we can create the forms and stuff first
